"""PolyPredictor model layer: classifier, baselines, and ensemble logic.

The layering used throughout this package:

  1. :mod:`model.classifier` assigns a :class:`MarketType` to every market.
  2. :mod:`model.baselines` computes a type-specific prior ``p_base``.
  3. :mod:`model.ensemble` refines ``p_base`` with persisted microstructure
     features and a per-type calibrator.

The live API still serves the baseline path today; the ensemble machinery is
implemented here and can be wired into serving once API/UI provenance extends
beyond the current baseline-source badge.
"""

from .backtest import (
    ROLLING_WINDOWS_DEFAULT,
    TTR_BUCKETS_DEFAULT,
    AutoDisableDecision,
    DailySkillSample,
    RollingWindowReport,
    StratumReport,
    WalkForwardReport,
    WalkForwardSample,
    brier_skill,
    expected_calibration_error,
    kl_divergence,
    population_stability_index,
    rolling_window_reports,
    should_auto_disable,
    walk_forward_evaluate,
)
from .baselines import (
    BaselineInputs,
    BaselineOutput,
    discrete_event_baseline,
    long_tail_baseline,
    multi_outcome_baseline,
    range_baseline,
    threshold_baseline,
)
from .classifier import ClassificationResult, MarketFeatures, classify
from .conformal import (
    ConformalCell,
    ConformalSample,
    PurgedFold,
    SplitConformalRegistry,
    fit_split_conformal,
    fit_split_conformal_from_folds,
    mondrian_key,
    mondrian_key_with_regime,
    purged_embargo_splits,
    ttr_bucket,
)
from .deribit import DeribitClient, DeribitIV, DeribitTermStructurePoint
from .ensemble import (
    BOOSTER_FEATURE_NAMES,
    LINEAR_FEATURE_NAMES,
    EnsembleRegistry,
    EnsembleSample,
    FeatureContribution,
    GradientBoostStump,
    IsotonicCalibrator,
    PredictionExplanation,
    TypeEnsembleModel,
    fit_per_type_ensembles,
)
from .external_venue import (
    BinanceDailyKline,
    BinanceKlinesClient,
    BinancePerpClient,
    BinancePerpSnapshot,
    BinanceSpotClient,
    CoinbaseIntxPerpClient,
    CoinbaseIntxPerpSnapshot,
    CoinbaseSpotClient,
    CoinGeckoSpotClient,
    SpotTickerSnapshot,
    SpotValidationResult,
    options_implied_probability,
    perp_basis_implied_probability,
    validate_spot_quotes,
)
from .pipeline import PipelineResult, probability_for_market
from .regime import (
    RegimeFeatures,
    RegimeLabel,
    RegimeResult,
    RegimeThresholds,
    regime_features_from_btc_closes,
    tag_regime,
)
from .resolution_risk import ResolutionRiskResult, score_resolution_risk
from .sibling_arb import (
    ArbViolation,
    MultiOutcomeGroup,
    OrderedThresholdPair,
    SiblingMarket,
    SiblingPrior,
    SiblingQuote,
    build_multi_outcome_groups,
    build_threshold_pairs,
    detect_multi_outcome_arbs,
    detect_threshold_arbs,
    sibling_prior_for_market,
)
from .types import BaselineSource, MarketType

__all__ = [
    "BOOSTER_FEATURE_NAMES",
    "LINEAR_FEATURE_NAMES",
    "ROLLING_WINDOWS_DEFAULT",
    "TTR_BUCKETS_DEFAULT",
    "ArbViolation",
    "AutoDisableDecision",
    "BaselineInputs",
    "BaselineOutput",
    "BaselineSource",
    "BinanceDailyKline",
    "BinanceKlinesClient",
    "BinancePerpClient",
    "BinancePerpSnapshot",
    "BinanceSpotClient",
    "ClassificationResult",
    "CoinGeckoSpotClient",
    "CoinbaseIntxPerpClient",
    "CoinbaseIntxPerpSnapshot",
    "CoinbaseSpotClient",
    "ConformalCell",
    "ConformalSample",
    "DailySkillSample",
    "DeribitClient",
    "DeribitIV",
    "DeribitTermStructurePoint",
    "EnsembleRegistry",
    "EnsembleSample",
    "FeatureContribution",
    "GradientBoostStump",
    "IsotonicCalibrator",
    "MarketFeatures",
    "MarketType",
    "MultiOutcomeGroup",
    "OrderedThresholdPair",
    "PipelineResult",
    "PredictionExplanation",
    "PurgedFold",
    "RegimeFeatures",
    "RegimeLabel",
    "RegimeResult",
    "RegimeThresholds",
    "ResolutionRiskResult",
    "RollingWindowReport",
    "SiblingMarket",
    "SiblingPrior",
    "SiblingQuote",
    "SplitConformalRegistry",
    "SpotTickerSnapshot",
    "SpotValidationResult",
    "StratumReport",
    "TypeEnsembleModel",
    "WalkForwardReport",
    "WalkForwardSample",
    "brier_skill",
    "build_multi_outcome_groups",
    "build_threshold_pairs",
    "classify",
    "detect_multi_outcome_arbs",
    "detect_threshold_arbs",
    "discrete_event_baseline",
    "expected_calibration_error",
    "fit_per_type_ensembles",
    "fit_split_conformal",
    "fit_split_conformal_from_folds",
    "kl_divergence",
    "long_tail_baseline",
    "mondrian_key",
    "mondrian_key_with_regime",
    "multi_outcome_baseline",
    "options_implied_probability",
    "perp_basis_implied_probability",
    "population_stability_index",
    "probability_for_market",
    "purged_embargo_splits",
    "range_baseline",
    "regime_features_from_btc_closes",
    "rolling_window_reports",
    "score_resolution_risk",
    "should_auto_disable",
    "sibling_prior_for_market",
    "tag_regime",
    "threshold_baseline",
    "ttr_bucket",
    "validate_spot_quotes",
    "walk_forward_evaluate",
]
